### ISSUE TITLE
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' 

### ISSUE THREAD

**Issue by nihilisticneuralnet** [MooreThreads/Moore-AnimateAnyone#13]
```
Traceback (most recent call last):
  File "Moore-AnimateAnyone\app.py", line 16, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "Moore-AnimateAnyone\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "Moore-AnimateAnyone\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "Moore-AnimateAnyone\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import CaptionProjection
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' 
```

**Comment by MrForExample** [comment]
You have this error because you are using newest diffusers library

To fix, in transformer_2d.py:

Replace `CaptionProjection` with `PixArtAlphaTextProjection`

**Comment by nihilisticneuralnet** [comment]
Thanks. that resolved the error.
