### ISSUE TITLE
ModuleNotFoundError: No module named 'tracker'

### ISSUE THREAD

**Issue by ayu2hami** [MooreThreads/Moore-AnimateAnyone#131]
I used anaconda virtual environment and also .venv python 3.10 - tested on both. I also tested it in python 3.11.
When installed dependencies i tried to make inference for Face Reenactment and got this error:
```
python -m scripts.lmks2vid --config ./configs/prompts/inference_reenact.yaml --driving_video_path "S:\AIprograms\AnimateAnyone\configs\inference\video\test4.mp4" --source_image_path "S:\AIprograms\AnimateAnyone\configs\inference\ref_images\test4.png"
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.0)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "C:\Users\benia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\benia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\AIprograms\AnimateAnyone\scripts\lmks2vid.py", line 34, in <module>
    from tools.facetracker_api import face_image
  File "S:\AIprograms\AnimateAnyone\tools\facetracker_api.py", line 7, in <module>
    from tracker import Tracker, get_model_base_path
ModuleNotFoundError: No module named 'tracker'
```

and after pip install tracker i get this error:
```
python -m scripts.lmks2vid --config ./configs/prompts/inference_reenact.yaml --driving_video_path "S:\AIprograms\AnimateAnyone\configs\inference\video\test4.mp4" --source_image_path "S:\AIprograms\AnimateAnyoneAlibaba\configs\inference\ref_images\test4.png"
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.0)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "C:\Users\benia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\benia\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\AIprograms\AnimateAnyone\scripts\lmks2vid.py", line 34, in <module>
    from tools.facetracker_api import face_image
  File "S:\AIprograms\AnimateAnyone\tools\facetracker_api.py", line 7, in <module>
    from tracker import Tracker, get_model_base_path
  File "S:\AIprograms\AnimateAnyone\.venv\lib\site-packages\tracker\__init__.py", line 1, in <module>
    from .tracker import tracked
  File "S:\AIprograms\AnimateAnyone\.venv\lib\site-packages\tracker\tracker.py", line 4, in <module>
    from .snapshot import Snapshot
  File "S:\AIprograms\AnimateAnyone\.venv\lib\site-packages\tracker\snapshot.py", line 2, in <module>
    from itertools import izip_longest
ImportError: cannot import name 'izip_longest' from 'itertools' (unknown location)
```

I tried to change "izip" to "zip" in "snapshot.py" but error still persists.
```
(AniANY311) S:\AIprograms\AnimateAnyone>python -m scripts.lmks2vid --config ./configs/prompts/inference_reenact.yaml --driving_video_path "S:\AIprograms\AnimateAnyone\configs\inference\video\test4.mp4" --source_image_path "S:\AIprograms\AnimateAnyone\configs\inference\ref_images\test4.png"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "S:\AIprograms\AnimateAnyone\scripts\lmks2vid.py", line 34, in <module>
    from tools.facetracker_api import face_image
  File "S:\AIprograms\AnimateAnyone\tools\facetracker_api.py", line 7, in <module>
    from tracker import Tracker, get_model_base_path
ImportError: cannot import name 'Tracker' from 'tracker'
```

Any ideas? My conclusion is that there is some lack of dependencies in requirements.txt or repo is missing some necessary libraries - "tracker" because "facetracker_api.py" can't import "Tracker" from "tracker" (?)

**Comment by liangyang-mt** [comment]
Thank you for following our work. Before face reenactment inference, did you execute this command: git clone https://github.com/emilianavt/OpenSeeFace.git, or download OpenSeeFace.zip and unzip it in the current directory?

**Comment by ayu2hami** [comment]
> Thank you for following our work. Before face reenactment inference, did you execute this command: git clone https://github.com/emilianavt/OpenSeeFace.git or download OpenSeeFace.zip and unzip it in the current directory? The "tracker" module is from [OpenSeeFace](https://github.com/emilianavt/OpenSeeFace).

I was sure I did this step, but I couldn't find OpenSeeFace in my directory. I did it once again now and I was able to pass this error. 
Thank you. But now appear another problem, I tried to resolve it with different versions of CUDA, I reinstall whole env, dependencies few times and still get the same error:

```
S:\anaconda3\envs\AnimAny\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
------------------initial all networks------------------
---------load pretrained denoising unet, reference unet and pose guider----------
2024-05-24 09:48:39.7883124 [E:onnxruntime:Default, provider_bridge_ort.cc:1730 onnxruntime::TryGetProviderInfo_TensorRT] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-05-24 09:48:41.0513825 [E:onnxruntime:, inference_session.cc:2045 onnxruntime::InferenceSession::Initialize::<lambda_d4e0caa0782683b2ee97e3859f73dc9c>::operator ()] Exception during initialization: C:\a\_work\1\s\onnxruntime\contrib_ops\cuda\fused_conv.cc:19 onnxruntime::contrib::cuda::FusedConv<float>::FusedConv [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"

Traceback (most recent call last):
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 469, in _create_inference_session
    self._register_ep_custom_ops(session_options, providers, provider_options, available_providers)
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 516, in _register_ep_custom_ops
    C.register_tensorrt_plugins_as_custom_ops(session_options, provider_options[i])
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\anaconda3\envs\AnimAny\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "S:\anaconda3\envs\AnimAny\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\AIprograms\AnimateAnyone\scripts\lmks2vid.py", line 337, in <module>
    main()
  File "S:\AIprograms\AnimateAnyone\scripts\lmks2vid.py", line 258, in main
    ref_pose, ref_pose_lms = face_image(ref_image)
  File "S:\AIprograms\AnimateAnyone\tools\facetracker_api.py", line 14, in face_image
    tracker = Tracker(width, height, threshold=None, max_threads=1, max_faces=1, discard_after=10, scan_every=3, silent=False, model_type=3, model_dir=None,
  File "S:\AIprograms\AnimateAnyone\OpenSeeFace\tracker.py", line 526, in __init__
    self.retinaface = RetinaFaceDetector(model_path=os.path.join(model_base_path, "retinaface_640x640_opt.onnx"), json_path=os.path.join(model_base_path, "priorbox_640x640.json"), threads=max(max_threads,4), top_k=max_faces, res=(640, 640))
  File "S:\AIprograms\AnimateAnyone\OpenSeeFace\retinaface.py", line 70, in __init__
    self.session = onnxruntime.InferenceSession(model_path, sess_options=options, providers=providersList)
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "S:\anaconda3\envs\AnimAny\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: C:\a\_work\1\s\onnxruntime\contrib_ops\cuda\fused_conv.cc:19 onnxruntime::contrib::cuda::FusedConv<float>::FusedConv [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"
```

**Comment by EzrealoveQXY** [comment]
thanks！
