### ISSUE TITLE
stag2 erro!!!!!!!!!! how to sovle it?

### ISSUE THREAD

**Issue by obtuseanglor** [MooreThreads/Moore-AnimateAnyone#133]
Traceback (most recent call last):
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/train_stage_2.py", line 773, in <module>
    main(config)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/train_stage_2.py", line 602, in main
    model_pred = net(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/train_stage_2.py", line 96, in forward
    model_pred = self.denoising_unet(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/unet_3d.py", line 514, in forward
    sample, res_samples = downsample_block(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/unet_3d_blocks.py", line 451, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/unet_3d_blocks.py", line 442, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/transformer_3d.py", line 159, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/transformer_3d.py", line 153, in custom_forward
    return module(*inputs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/mutual_self_attention.py", line 151, in hacked_basic_transformer_inner_forward
    bank_fea = [
  File "/root/node03-nfs/model/Moore-AnimateAnyone-master/src/models/mutual_self_attention.py", line 153, in <listcomp>
    d.unsqueeze(1).repeat(1, video_length, 1, 1),
TypeError: repeat(): argument 'repeats' must be tuple of ints, but found element of type NoneType at pos 2

**Comment by liangyang-mt** [comment]
This is a parameter passing bug. [Some parameters](https://github.com/MooreThreads/Moore-AnimateAnyone/blob/163333d5da32083acb3410ddbbc0b1a7282d1e4b/src/models/transformer_3d.py#L165) are mismatched. It has been fixed. You can try again after updating the code.

**Comment by obtuseanglor** [comment]
谢谢您！！

**Comment by obtuseanglor** [comment]
Traceback (most recent call last):
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 773, in <module>
    main(config)
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 602, in main
    model_pred = net(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 96, in forward
    model_pred = self.denoising_unet(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/src/models/unet_3d.py", line 514, in forward
    sample, res_samples = downsample_block(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/src/models/unet_3d_blocks.py", line 451, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 246, in checkpoint
    raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwargs))
ValueError: Unexpected keyword arguments: encoder_hidden_states,self_attention_additional_feats,mode

**Comment by obtuseanglor** [comment]
hi I'm getting a new error when I run it, what is the reason for this?

**Comment by obtuseanglor** [comment]
hi I'm getting a new error when I run it, what is the reason for this?

**Comment by obtuseanglor** [comment]
Traceback (most recent call last):
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 773, in <module>
    main(config)
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 602, in main
    model_pred = net(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/train_stage_2.py", line 96, in forward
    model_pred = self.denoising_unet(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/src/models/unet_3d.py", line 514, in forward
    sample, res_samples = downsample_block(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/node03-nfs/model/baseline_model/src/models/unet_3d_blocks.py", line 451, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/root/anaconda3/envs/animate/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 246, in checkpoint
    raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwargs))
ValueError: Unexpected keyword arguments: encoder_hidden_states,self_attention_additional_feats,mode

**Comment by BoyuanJiang** [comment]
same problem

**Comment by sdan** [comment]
Issue can be fixed by playing with torch version or by enabling `gradient_checkpointing = False` in `stage2.yaml`.

One thing I tried was using a different version of torch which seemed to fix the issue once `pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118`

Otherwise your best bet is to turn off gradient checkpointing, unsure why exactly, we were running into the same issue if we turned on gradient checkpointing in `stage1.yaml` too

**Comment by aleeyang** [comment]
> same problem

I find a possible solution, you can use the src code from MusePose to replace the src mode here. It works!
https://github.com/TMElyralab/MusePose
