### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading file data/383: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by zachysaur** [MooreThreads/Moore-AnimateAnyone#21]
RuntimeError: PytorchStreamReader failed reading file data/383: invalid header or archive is corrupted

**Comment by lixunsong** [comment]
It seems the downloaded weights are broken

**Comment by zachysaur** [comment]
how can i fix it

**Comment by zachysaur** [comment]
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
C:\Users\ggrov\anaconda3\envs\animate\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Animate\Moore-AnimateAnyone-master\scripts\pose2vid.py", line 167, in <module>
    main()
  File "F:\Animate\Moore-AnimateAnyone-master\scripts\pose2vid.py", line 91, in main
    torch.load(config.reference_unet_path, map_location="cpu"),
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\site-packages\torch\serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\ggrov\anaconda3\envs\animate\lib\site-packages\torch\serialization.py", line 1357, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/383: invalid header or archive is corrupted

**Comment by lixunsong** [comment]
There is a installation guider for windows users. You can try it: https://github.com/sdbds/Moore-AnimateAnyone-for-windows
