### ISSUE TITLE
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./pretrained_weights/sd-vae-ft-mse.

### ISSUE THREAD

**Issue by wotise** [MooreThreads/Moore-AnimateAnyone#93]
I ran the app.py on colab. When I clicked the [Animate] button, the error occurred. Here is the detail message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/Moore-AnimateAnyone-master/app.py", line 48, in animate
    vae = AutoencoderKL.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 777, in from_pretrained
    model_file = _get_model_file(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/hub_utils.py", line 284, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory ./pretrained_weights/sd-vae-ft-mse.

Here is my filepath on colab.
![708c9201-7625-4093-9e14-c0bbfdcb20ab](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/59403146/b9610f4d-8a68-4a1e-89ee-07d2ab2c32f2)
Can anyone has idea to solve the problem? Thanks a lot!

**Comment by Tsaiyue** [comment]
As my experience, u could rerun the weight loading script and the error will dispear, while i do not know the ultimate reason now.

**Comment by lixunsong** [comment]
The model weights did not completely. Try to use our provided weight downloading scripts, and make sure your network can connect to huggingface.com successfully.

**Comment by Heisenberg301116** [comment]
Check if ./pretrained_weights/sd-vae-ft-mse contains 'diffusion_pytorch_model.bin' or not. And if yes, ensure it exactly matches with the name: 'diffusion_pytorch_model.bin'. I had to rename it by removing the trailing "002".
