### ISSUE TITLE
单卡4090开了DeepSpeed的offload跑200步报RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half

### ISSUE THREAD

**Issue by xiaoxiaolai** [MooreThreads/Moore-AnimateAnyone#99]
Steps:   1%|          | 200/30000 [28:37<59:09:16,  7.15s/it, lr=1e-5, step_loss=0.635]02/29/2024 13:49:07 - INFO - __main__ - Running validation... 
The passed generator was created on 'cpu' even though a tensor on cuda:0 was expected. Tensors will be created on 'cpu' and then moved to cuda:0. Note that one can probably slighly speed up this function by passing a generator that was created on the cuda:0 device.

  0%|          | 0/20 [00:00<?, ?it/s][A
  0%|          | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/train_stage_1.py", line 725, in <module>
    main(config)
  File "/workspace/train_stage_1.py", line 627, in main
    sample_dicts = log_validation(
  File "/workspace/train_stage_1.py", line 178, in log_validation
    image = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/src/pipelines/pipeline_pose2img.py", line 299, in __call__
    self.reference_unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/src/models/unet_2d_condition.py", line 1009, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/embeddings.py", line 228, in forward
    sample = self.linear_1(sample)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/lora.py", line 430, in forward
    out = super().forward(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half

**Comment by renrenzsbbb** [comment]
I also meet it. I solve it by commet the below code
`    # vae = vae.to(dtype=torch.float32)
    # image_enc = image_enc.to(dtype=torch.float32)`

**Comment by jasonfjptchh0821** [comment]
请问怎么使用deepspeed？

**Comment by l-dawei** [comment]
> I also meet it. I solve it by commet the below code ` vae = vae.to(dtype=torch.float32) image_enc = image_enc.to(dtype=torch.float32)`

The above code is included in the official code. Where did you add it?

**Comment by yiyuzhuang** [comment]
Hi! I encountered the same error in the **log_validation()** function in **train_stage_1.py**. I believe it's caused by the mismatch between the 'fp16' setting of the network and the 'torch.float32' inputs.

To fix this issue, I changed the following lines of code:
``` python
    # vae = vae.to(dtype=torch.float32) # line 145
    # image_enc = image_enc.to(dtype=torch.float32)
    vae = vae.to(dtype=reference_unet.dtype) # yy
    image_enc = image_enc.to(dtype=reference_unet.dtype) # yy
```
and
    ``` python
# vae = vae.to(dtype=torch.float16)  # line 203
    # image_enc = image_enc.to(dtype=torch.float16)
```
By setting the data type of the inputs vae and image_enc to match the data type of the model reference_unet, I was able to resolve the error. If there's a better solution or any suggestions, please let me know.

**Comment by ButoneDream** [comment]
thanks a lot

**Comment by Kebii** [comment]
I meet the OOM problem when running it on 4090 GPU. How did you set the config file of the accelerator and deepspeed? I would greatly appreciate it if you could provide any suggestions.

**Comment by xiaoxiaolai** [comment]
> I meet the OOM problem when running it on 4090 GPU. How did you set the config file of the accelerator and deepspeed? I would greatly appreciate it if you could provide any suggestions.

参考https://huggingface.co/docs/accelerate/usage_guides/deepspeed
执行accelerate config
我是二阶段，然后打开了offload

**Comment by xiaoxiaolai** [comment]
200步是因为validation_steps默认200步，最后关闭了注释了验证代码

**Comment by Kebii** [comment]
> > > I meet the OOM problem when running it on 4090 GPU. How did you set the config file of the accelerator and deepspeed? I would greatly appreciate it if you could provide any suggestions.
> > 
> > 
> > 参考https://huggingface.co/docs/accelerate/usage_guides/deepspeed 执行accelerate config 我是二阶段，然后打开了offload
> 
> 感谢回复，我尝试用deepspeed，打开offload，但是会报错：AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam' 看起来像是版本问题，但我的环境和这个代码的requirements是一致的

也许我定位到问题了，请问你的CUDA和pytorch分别是什么版本呀？
